#!/usr/bin/env bash
# install.sh — Set up pan-os-php for local CLI use
#
# Requirements: PHP 8.3 (php-legacy on Arch/EndeavourOS), jq
# Run as root or with sudo.
#
# What this script does:
#   1. Installs php-legacy (PHP 8.3) and jq via pacman if not present
#   2. Enables the bcmath extension for php-legacy
#   3. Installs a /usr/local/bin/pan-os-php wrapper pointing at this repo
#   4. Installs bash completion into /etc/bash_completion.d/

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PHP_BIN="php-legacy"
PHP_CONF_D="/etc/php-legacy/conf.d"
WRAPPER="/usr/local/bin/pan-os-php"
COMPLETION_DEST="/etc/bash_completion.d/pan-os-php"
COMPLETION_SRC="${REPO_DIR}/utils/bash_autocompletion/pan-os-php.sh"
ENTRY_POINT="${REPO_DIR}/utils/pan-os-php.php"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[+]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "Please run as root: sudo ./install.sh"
fi

# ── 1. Install php-legacy and jq ─────────────────────────────────────────────
info "Checking dependencies..."

PKGS_TO_INSTALL=()
if ! command -v php-legacy &>/dev/null; then
    PKGS_TO_INSTALL+=(php-legacy)
fi
if ! command -v jq &>/dev/null; then
    PKGS_TO_INSTALL+=(jq)
fi

if [[ ${#PKGS_TO_INSTALL[@]} -gt 0 ]]; then
    info "Installing: ${PKGS_TO_INSTALL[*]}"
    pacman -S --noconfirm "${PKGS_TO_INSTALL[@]}"
else
    info "php-legacy and jq already installed."
fi

PHP_VERSION=$(php-legacy --version | head -1)
info "Using: ${PHP_VERSION}"

# ── 2. Enable bcmath extension ───────────────────────────────────────────────
BCMATH_INI="${PHP_CONF_D}/pan-os-php.ini"
if [[ ! -f "${BCMATH_INI}" ]]; then
    info "Enabling bcmath extension for php-legacy..."
    mkdir -p "${PHP_CONF_D}"
    cat > "${BCMATH_INI}" <<'EOF'
; Enabled for pan-os-php
extension=bcmath
EOF
    info "Created ${BCMATH_INI}"
else
    info "bcmath ini already present at ${BCMATH_INI}"
fi

# Verify bcmath loads
if ! php-legacy -m 2>/dev/null | grep -q bcmath; then
    error "bcmath failed to load — check ${BCMATH_INI}"
fi
info "bcmath extension: OK"

# ── 3. Verify all required extensions are available ──────────────────────────
info "Verifying required extensions (curl, dom, mbstring, bcmath)..."
for EXT in curl dom mbstring bcmath; do
    if php-legacy -m 2>/dev/null | grep -qi "^${EXT}$"; then
        info "  ${EXT}: OK"
    else
        error "  ${EXT}: MISSING — install php-legacy-${EXT} or enable it in /etc/php-legacy/php.ini"
    fi
done

# ── 4. Install wrapper script ─────────────────────────────────────────────────
info "Installing wrapper to ${WRAPPER}..."
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# pan-os-php wrapper — auto-generated by ${REPO_DIR}/install.sh
exec php-legacy "${ENTRY_POINT}" "\$@"
EOF
chmod 755 "${WRAPPER}"
info "Wrapper installed: ${WRAPPER}"

# ── 5. Install bash completion ────────────────────────────────────────────────
info "Installing bash completion to ${COMPLETION_DEST}..."
# Symlink so the script can resolve its own path back to the repo
# (the autocomplete uses readlink -f to locate util_action_filter.json)
ln -sf "${COMPLETION_SRC}" "${COMPLETION_DEST}"
info "Bash completion installed: ${COMPLETION_DEST} -> ${COMPLETION_SRC}"

# ── 6. Add completion to shell rc files (for the invoking user) ───────────────
# Determine the real user when run via sudo
REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "${REAL_USER}" | cut -d: -f6)

BASH_SNIPPET="source ${COMPLETION_DEST}"
ZSH_SNIPPET="# pan-os-php completion (tab completion not yet supported in zsh upstream)
autoload bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
source ${COMPLETION_DEST} 2>/dev/null"

for RC in "${REAL_HOME}/.bashrc" "${REAL_HOME}/.bash_profile"; do
    if [[ -f "${RC}" ]]; then
        if ! grep -q "pan-os-php" "${RC}"; then
            echo "" >> "${RC}"
            echo "# pan-os-php completion" >> "${RC}"
            echo "${BASH_SNIPPET}" >> "${RC}"
            info "Added completion to ${RC}"
        else
            info "Completion already present in ${RC}"
        fi
    fi
done

ZSHRC="${REAL_HOME}/.zshrc"
if [[ -f "${ZSHRC}" ]]; then
    if ! grep -q "pan-os-php" "${ZSHRC}"; then
        echo "" >> "${ZSHRC}"
        echo "${ZSH_SNIPPET}" >> "${ZSHRC}"
        info "Added completion to ${ZSHRC}"
    else
        info "Completion already present in ${ZSHRC}"
    fi
fi

# ── 7. Smoke test ─────────────────────────────────────────────────────────────
info "Running smoke test: pan-os-php version"
"${WRAPPER}" version 2>&1 | head -3

echo
info "Installation complete."
echo
echo "  Usage:  pan-os-php type=rule in=config.xml actions=display"
echo
echo "  Note: tab completion works in bash; zsh support is not yet"
echo "  implemented upstream (the command itself works fine in zsh)."
echo
